FROM golang:1.10-alpine
WORKDIR /go/src/github.com/devops-test-foxintelligence/backend
ADD .  /go/src/github.com/devops-test-foxintelligence/backend
RUN apk add git
RUN adduser -S -D -H -h /app luser
RUN go get -u github.com/golang/dep/cmd/dep && dep ensure && go get && go build -o /app/main . && rm -rf /go
USER luser
WORKDIR /app
CMD ["./main"]
